package cc.factorie.app.nlp.lexicon.en.minor

import cc.factorie.app.nlp.lexicon.ProvidedTriePhraseLexicon
import cc.factorie.util.ModelProvider

/**
  * Created by Robert on 2016/7/18.
  */


class BaseFightCrimeTypeFree()(implicit mp: ModelProvider[BaseFightCrimeTypeFree]) extends ProvidedTriePhraseLexicon[BaseFightCrimeTypeFree]
class BusinessDisambiguationWiki()(implicit mp: ModelProvider[BusinessDisambiguationWiki]) extends ProvidedTriePhraseLexicon[BusinessDisambiguationWiki]
class BusinessJobTitleFree()(implicit mp: ModelProvider[BusinessJobTitleFree]) extends ProvidedTriePhraseLexicon[BusinessJobTitleFree]
class BusinessParenWiki()(implicit mp: ModelProvider[BusinessParenWiki]) extends ProvidedTriePhraseLexicon[BusinessParenWiki]
class BusinessRedirectParenWiki()(implicit mp: ModelProvider[BusinessRedirectParenWiki]) extends ProvidedTriePhraseLexicon[BusinessRedirectParenWiki]
class BusinessRedirectWiki()(implicit mp: ModelProvider[BusinessRedirectWiki]) extends ProvidedTriePhraseLexicon[BusinessRedirectWiki]
class BusinessWiki()(implicit mp: ModelProvider[BusinessWiki]) extends ProvidedTriePhraseLexicon[BusinessWiki]
class CityIesl()(implicit mp: ModelProvider[CityIesl]) extends ProvidedTriePhraseLexicon[CityIesl]
class CityParenWiki()(implicit mp: ModelProvider[CityParenWiki]) extends ProvidedTriePhraseLexicon[CityParenWiki]
class CityRedirectParenWiki()(implicit mp: ModelProvider[CityRedirectParenWiki]) extends ProvidedTriePhraseLexicon[CityRedirectParenWiki]
class CityRedirectWiki()(implicit mp: ModelProvider[CityRedirectWiki]) extends ProvidedTriePhraseLexicon[CityRedirectWiki]
class CityWiki()(implicit mp: ModelProvider[CityWiki]) extends ProvidedTriePhraseLexicon[CityWiki]
class CompanyIesl()(implicit mp: ModelProvider[CompanyIesl]) extends ProvidedTriePhraseLexicon[CompanyIesl]
class CountryIesl()(implicit mp: ModelProvider[CountryIesl]) extends ProvidedTriePhraseLexicon[CountryIesl]
class CountryParenWiki()(implicit mp: ModelProvider[CountryParenWiki]) extends ProvidedTriePhraseLexicon[CountryParenWiki]
class CountryRedirectParenWiki()(implicit mp: ModelProvider[CountryRedirectParenWiki]) extends ProvidedTriePhraseLexicon[CountryRedirectParenWiki]
class CountryRedirectWiki()(implicit mp: ModelProvider[CountryRedirectWiki]) extends ProvidedTriePhraseLexicon[CountryRedirectWiki]
class CountryWiki()(implicit mp: ModelProvider[CountryWiki]) extends ProvidedTriePhraseLexicon[CountryWiki]
class EducationEducationalInstitutionFree()(implicit mp: ModelProvider[EducationEducationalInstitutionFree]) extends ProvidedTriePhraseLexicon[EducationEducationalInstitutionFree]
class GovernmentPoliticalDistrictFree()(implicit mp: ModelProvider[GovernmentPoliticalDistrictFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalDistrictFree]
class GovernmentPoliticalIdeologyFree()(implicit mp: ModelProvider[GovernmentPoliticalIdeologyFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalIdeologyFree]
class GovernmentPoliticalPartyFree()(implicit mp: ModelProvider[GovernmentPoliticalPartyFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalPartyFree]
class JobTitleIesl()(implicit mp: ModelProvider[JobTitleIesl]) extends ProvidedTriePhraseLexicon[JobTitleIesl]
class JobtitleIesl()(implicit mp: ModelProvider[JobtitleIesl]) extends ProvidedTriePhraseLexicon[JobtitleIesl]
class LawLegalSubjectFree()(implicit mp: ModelProvider[LawLegalSubjectFree]) extends ProvidedTriePhraseLexicon[LawLegalSubjectFree]
class LocationAdministrativeDivisionFree()(implicit mp: ModelProvider[LocationAdministrativeDivisionFree]) extends ProvidedTriePhraseLexicon[LocationAdministrativeDivisionFree]
class LocationCitytownFree()(implicit mp: ModelProvider[LocationCitytownFree]) extends ProvidedTriePhraseLexicon[LocationCitytownFree]
class LocationCountryFree()(implicit mp: ModelProvider[LocationCountryFree]) extends ProvidedTriePhraseLexicon[LocationCountryFree]
class LocationDisambiguationWiki()(implicit mp: ModelProvider[LocationDisambiguationWiki]) extends ProvidedTriePhraseLexicon[LocationDisambiguationWiki]
class LocationParenWiki()(implicit mp: ModelProvider[LocationParenWiki]) extends ProvidedTriePhraseLexicon[LocationParenWiki]
class LocationRedirectParenWiki()(implicit mp: ModelProvider[LocationRedirectParenWiki]) extends ProvidedTriePhraseLexicon[LocationRedirectParenWiki]
class LocationRedirectWiki()(implicit mp: ModelProvider[LocationRedirectWiki]) extends ProvidedTriePhraseLexicon[LocationRedirectWiki]
class LocationWiki()(implicit mp: ModelProvider[LocationWiki]) extends ProvidedTriePhraseLexicon[LocationWiki]
class OrgSuffixIesl()(implicit mp: ModelProvider[OrgSuffixIesl]) extends ProvidedTriePhraseLexicon[OrgSuffixIesl]
class OrganizationDisambiguationWiki()(implicit mp: ModelProvider[OrganizationDisambiguationWiki]) extends ProvidedTriePhraseLexicon[OrganizationDisambiguationWiki]
class OrganizationOrganizationFree()(implicit mp: ModelProvider[OrganizationOrganizationFree]) extends ProvidedTriePhraseLexicon[OrganizationOrganizationFree]
class OrganizationOrganizationSectorFree()(implicit mp: ModelProvider[OrganizationOrganizationSectorFree]) extends ProvidedTriePhraseLexicon[OrganizationOrganizationSectorFree]
class OrganizationParenWiki()(implicit mp: ModelProvider[OrganizationParenWiki]) extends ProvidedTriePhraseLexicon[OrganizationParenWiki]
class OrganizationRedirectParenWiki()(implicit mp: ModelProvider[OrganizationRedirectParenWiki]) extends ProvidedTriePhraseLexicon[OrganizationRedirectParenWiki]
class OrganizationRedirectWiki()(implicit mp: ModelProvider[OrganizationRedirectWiki]) extends ProvidedTriePhraseLexicon[OrganizationRedirectWiki]
class OrganizationWiki()(implicit mp: ModelProvider[OrganizationWiki]) extends ProvidedTriePhraseLexicon[OrganizationWiki]
class PeopleCauseOfDeathFree()(implicit mp: ModelProvider[PeopleCauseOfDeathFree]) extends ProvidedTriePhraseLexicon[PeopleCauseOfDeathFree]
class PeoplePersonFree()(implicit mp: ModelProvider[PeoplePersonFree]) extends ProvidedTriePhraseLexicon[PeoplePersonFree]
class PeopleProfessionFree()(implicit mp: ModelProvider[PeopleProfessionFree]) extends ProvidedTriePhraseLexicon[PeopleProfessionFree]
class PersonDisambiguationWiki()(implicit mp: ModelProvider[PersonDisambiguationWiki]) extends ProvidedTriePhraseLexicon[PersonDisambiguationWiki]
class PersonFirstHighIesl()(implicit mp: ModelProvider[PersonFirstHighIesl]) extends ProvidedTriePhraseLexicon[PersonFirstHighIesl]
class PersonFirstHighestIesl()(implicit mp: ModelProvider[PersonFirstHighestIesl]) extends ProvidedTriePhraseLexicon[PersonFirstHighestIesl]
class PersonFirstMediumIesl()(implicit mp: ModelProvider[PersonFirstMediumIesl]) extends ProvidedTriePhraseLexicon[PersonFirstMediumIesl]
class PersonHonorificIesl()(implicit mp: ModelProvider[PersonHonorificIesl]) extends ProvidedTriePhraseLexicon[PersonHonorificIesl]
class PersonLastHighIesl()(implicit mp: ModelProvider[PersonLastHighIesl]) extends ProvidedTriePhraseLexicon[PersonLastHighIesl]
class PersonLastHighestIesl()(implicit mp: ModelProvider[PersonLastHighestIesl]) extends ProvidedTriePhraseLexicon[PersonLastHighestIesl]
class PersonLastMediumIesl()(implicit mp: ModelProvider[PersonLastMediumIesl]) extends ProvidedTriePhraseLexicon[PersonLastMediumIesl]
class PersonParenWiki()(implicit mp: ModelProvider[PersonParenWiki]) extends ProvidedTriePhraseLexicon[PersonParenWiki]
class PersonRedirectParenWiki()(implicit mp: ModelProvider[PersonRedirectParenWiki]) extends ProvidedTriePhraseLexicon[PersonRedirectParenWiki]
class PersonRedirectWiki()(implicit mp: ModelProvider[PersonRedirectWiki]) extends ProvidedTriePhraseLexicon[PersonRedirectWiki]
class PersonWiki()(implicit mp: ModelProvider[PersonWiki]) extends ProvidedTriePhraseLexicon[PersonWiki]
class ReligionReligionFree()(implicit mp: ModelProvider[ReligionReligionFree]) extends ProvidedTriePhraseLexicon[ReligionReligionFree]
class ReligionReligiousOrganizationFree()(implicit mp: ModelProvider[ReligionReligiousOrganizationFree]) extends ProvidedTriePhraseLexicon[ReligionReligiousOrganizationFree]
