package cc.factorie.app.nlp.lexicon.major

import cc.factorie.app.nlp.lexicon.ProvidedTriePhraseLexicon
import cc.factorie.util.ModelProvider

/**
  * Created by Robert on 2016/7/1.
  */


class BaseFightCrimeTypeFree()(implicit mp: ModelProvider[BaseFightCrimeTypeFree]) extends ProvidedTriePhraseLexicon[BaseFightCrimeTypeFree]
class BookWiki()(implicit mp: ModelProvider[BookWiki]) extends ProvidedTriePhraseLexicon[BookWiki]
class BusinessJobTitleFree()(implicit mp: ModelProvider[BusinessJobTitleFree]) extends ProvidedTriePhraseLexicon[BusinessJobTitleFree]
class BusinessWiki()(implicit mp: ModelProvider[BusinessWiki]) extends ProvidedTriePhraseLexicon[BusinessWiki]
class ContinentsIesl()(implicit mp: ModelProvider[ContinentsIesl]) extends ProvidedTriePhraseLexicon[ContinentsIesl]
class DayIesl()(implicit mp: ModelProvider[DayIesl]) extends ProvidedTriePhraseLexicon[DayIesl]
class DemonymIesl()(implicit mp: ModelProvider[DemonymIesl]) extends ProvidedTriePhraseLexicon[DemonymIesl]
class EducationEducationalInstitutionFree()(implicit mp: ModelProvider[EducationEducationalInstitutionFree]) extends ProvidedTriePhraseLexicon[EducationEducationalInstitutionFree]
class EventWiki()(implicit mp: ModelProvider[EventWiki]) extends ProvidedTriePhraseLexicon[EventWiki]
class FilmWiki()(implicit mp: ModelProvider[FilmWiki]) extends ProvidedTriePhraseLexicon[FilmWiki]
class FirstNameFemaleExtr()(implicit mp: ModelProvider[FirstNameFemaleExtr]) extends ProvidedTriePhraseLexicon[FirstNameFemaleExtr]
class FirstNameMaleExtr()(implicit mp: ModelProvider[FirstNameMaleExtr]) extends ProvidedTriePhraseLexicon[FirstNameMaleExtr]
class GovernmentPoliticalDistrictFree()(implicit mp: ModelProvider[GovernmentPoliticalDistrictFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalDistrictFree]
class GovernmentPoliticalIdeologyFree()(implicit mp: ModelProvider[GovernmentPoliticalIdeologyFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalIdeologyFree]
class GovernmentPoliticalPartyFree()(implicit mp: ModelProvider[GovernmentPoliticalPartyFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalPartyFree]
class LastNameExtr()(implicit mp: ModelProvider[LastNameExtr]) extends ProvidedTriePhraseLexicon[LastNameExtr]
class LawLegalSubjectFree()(implicit mp: ModelProvider[LawLegalSubjectFree]) extends ProvidedTriePhraseLexicon[LawLegalSubjectFree]
class LocationAdministrativeDivisionFree()(implicit mp: ModelProvider[LocationAdministrativeDivisionFree]) extends ProvidedTriePhraseLexicon[LocationAdministrativeDivisionFree]
class LocationCityOsmp()(implicit mp: ModelProvider[LocationCityOsmp]) extends ProvidedTriePhraseLexicon[LocationCityOsmp]
class LocationCityWiki()(implicit mp: ModelProvider[LocationCityWiki]) extends ProvidedTriePhraseLexicon[LocationCityWiki]
class LocationCitytownFree()(implicit mp: ModelProvider[LocationCitytownFree]) extends ProvidedTriePhraseLexicon[LocationCitytownFree]
class LocationCountryWiki()(implicit mp: ModelProvider[LocationCountryWiki]) extends ProvidedTriePhraseLexicon[LocationCountryWiki]
class LocationCountryFree()(implicit mp: ModelProvider[LocationCountryFree]) extends ProvidedTriePhraseLexicon[LocationCountryFree]
class LocationIesl()(implicit mp: ModelProvider[LocationIesl]) extends ProvidedTriePhraseLexicon[LocationIesl]
class LocationRedirectWiki()(implicit mp: ModelProvider[LocationRedirectWiki]) extends ProvidedTriePhraseLexicon[LocationRedirectWiki]
class LocationStateWiki()(implicit mp: ModelProvider[LocationStateWiki]) extends ProvidedTriePhraseLexicon[LocationStateWiki]
class LocationUndefinedWiki()(implicit mp: ModelProvider[LocationUndefinedWiki]) extends ProvidedTriePhraseLexicon[LocationUndefinedWiki]
class LocationWiki()(implicit mp: ModelProvider[LocationWiki]) extends ProvidedTriePhraseLexicon[LocationWiki]
class MiscellaneousIesl()(implicit mp: ModelProvider[MiscellaneousIesl]) extends ProvidedTriePhraseLexicon[MiscellaneousIesl]
class MonthIesl()(implicit mp: ModelProvider[MonthIesl]) extends ProvidedTriePhraseLexicon[MonthIesl]
class OrgSuffixIesl()(implicit mp: ModelProvider[OrgSuffixIesl]) extends ProvidedTriePhraseLexicon[OrgSuffixIesl]
class OrganizationIesl()(implicit mp: ModelProvider[OrganizationIesl]) extends ProvidedTriePhraseLexicon[OrganizationIesl]
class OrganizationOrganizationFree()(implicit mp: ModelProvider[OrganizationOrganizationFree]) extends ProvidedTriePhraseLexicon[OrganizationOrganizationFree]
class OrganizationOrganizationSectorFree()(implicit mp: ModelProvider[OrganizationOrganizationSectorFree]) extends ProvidedTriePhraseLexicon[OrganizationOrganizationSectorFree]
class OrganizationRedirectWiki()(implicit mp: ModelProvider[OrganizationRedirectWiki]) extends ProvidedTriePhraseLexicon[OrganizationRedirectWiki]
class OrganizationWiki()(implicit mp: ModelProvider[OrganizationWiki]) extends ProvidedTriePhraseLexicon[OrganizationWiki]
class PeopleCauseOfDeathFree()(implicit mp: ModelProvider[PeopleCauseOfDeathFree]) extends ProvidedTriePhraseLexicon[PeopleCauseOfDeathFree]
class PeoplePersonFree()(implicit mp: ModelProvider[PeoplePersonFree]) extends ProvidedTriePhraseLexicon[PeoplePersonFree]
class PeopleProfessionFree()(implicit mp: ModelProvider[PeopleProfessionFree]) extends ProvidedTriePhraseLexicon[PeopleProfessionFree]
class PersonFirstIesl()(implicit mp: ModelProvider[PersonFirstIesl]) extends ProvidedTriePhraseLexicon[PersonFirstIesl]
class PersonHonorificIesl()(implicit mp: ModelProvider[PersonHonorificIesl]) extends ProvidedTriePhraseLexicon[PersonHonorificIesl]
class PersonIesl()(implicit mp: ModelProvider[PersonIesl]) extends ProvidedTriePhraseLexicon[PersonIesl]
class PersonLastIesl()(implicit mp: ModelProvider[PersonLastIesl]) extends ProvidedTriePhraseLexicon[PersonLastIesl]
class PersonRedirectWiki()(implicit mp: ModelProvider[PersonRedirectWiki]) extends ProvidedTriePhraseLexicon[PersonRedirectWiki]
class PersonWiki()(implicit mp: ModelProvider[PersonWiki]) extends ProvidedTriePhraseLexicon[PersonWiki]
class ReligionReligionFree()(implicit mp: ModelProvider[ReligionReligionFree]) extends ProvidedTriePhraseLexicon[ReligionReligionFree]
class ReligionReligiousOrganizationFree()(implicit mp: ModelProvider[ReligionReligiousOrganizationFree]) extends ProvidedTriePhraseLexicon[ReligionReligiousOrganizationFree]
