package cc.factorie.app.nlp.lexicon.major

import cc.factorie.app.nlp.lexicon.ProvidedTriePhraseLexicon
import cc.factorie.util.ModelProvider

/**
  * Created by Robert on 2016/7/1.
  */


class BaseFightCrimeTypeFree()(implicit mp: ModelProvider[BaseFightCrimeTypeFree]) extends ProvidedTriePhraseLexicon[BaseFightCrimeTypeFree]
class BookWiki()(implicit mp: ModelProvider[BookWiki]) extends ProvidedTriePhraseLexicon[BookWiki]
class BusinessJobTitleFree()(implicit mp: ModelProvider[BusinessJobTitleFree]) extends ProvidedTriePhraseLexicon[BusinessJobTitleFree]
class BusinessWiki()(implicit mp: ModelProvider[BusinessWiki]) extends ProvidedTriePhraseLexicon[BusinessWiki]
class ContinentsIesl()(implicit mp: ModelProvider[ContinentsIesl]) extends ProvidedTriePhraseLexicon[ContinentsIesl]
class DayIesl()(implicit mp: ModelProvider[DayIesl]) extends ProvidedTriePhraseLexicon[DayIesl]
class DemonymIesl()(implicit mp: ModelProvider[DemonymIesl]) extends ProvidedTriePhraseLexicon[DemonymIesl]
class EducationEducationalInstitutionFree()(implicit mp: ModelProvider[EducationEducationalInstitutionFree]) extends ProvidedTriePhraseLexicon[EducationEducationalInstitutionFree]
class EventWiki()(implicit mp: ModelProvider[EventWiki]) extends ProvidedTriePhraseLexicon[EventWiki]
class FilmWiki()(implicit mp: ModelProvider[FilmWiki]) extends ProvidedTriePhraseLexicon[FilmWiki]
class FirstNameFemaleExtr()(implicit mp: ModelProvider[FirstNameFemaleExtr]) extends ProvidedTriePhraseLexicon[FirstNameFemaleExtr]
class FirstNameMaleExtr()(implicit mp: ModelProvider[FirstNameMaleExtr]) extends ProvidedTriePhraseLexicon[FirstNameMaleExtr]
class GovernmentPoliticalDistrictFree()(implicit mp: ModelProvider[GovernmentPoliticalDistrictFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalDistrictFree]
class GovernmentPoliticalIdeologyFree()(implicit mp: ModelProvider[GovernmentPoliticalIdeologyFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalIdeologyFree]
class GovernmentPoliticalPartyFree()(implicit mp: ModelProvider[GovernmentPoliticalPartyFree]) extends ProvidedTriePhraseLexicon[GovernmentPoliticalPartyFree]
class LastNameExtr()(implicit mp: ModelProvider[LastNameExtr]) extends ProvidedTriePhraseLexicon[LastNameExtr]
class LawLegalSubjectFree()(implicit mp: ModelProvider[LawLegalSubjectFree]) extends ProvidedTriePhraseLexicon[LawLegalSubjectFree]
class LocationAdministrativeDivisionFree()(implicit mp: ModelProvider[LocationAdministrativeDivisionFree]) extends ProvidedTriePhraseLexicon[LocationAdministrativeDivisionFree]
class LocationCityEnOsmp()(implicit mp: ModelProvider[LocationCityEnOsmp]) extends ProvidedTriePhraseLexicon[LocationCityEnOsmp]
class LocationCityEnWiki()(implicit mp: ModelProvider[LocationCityEnWiki]) extends ProvidedTriePhraseLexicon[LocationCityEnWiki]
class LocationCityEsOsmp()(implicit mp: ModelProvider[LocationCityEsOsmp]) extends ProvidedTriePhraseLexicon[LocationCityEsOsmp]
class LocationCityEsWiki()(implicit mp: ModelProvider[LocationCityEsWiki]) extends ProvidedTriePhraseLexicon[LocationCityEsWiki]
class LocationCitytownFree()(implicit mp: ModelProvider[LocationCitytownFree]) extends ProvidedTriePhraseLexicon[LocationCitytownFree]
class LocationCountryEnWiki()(implicit mp: ModelProvider[LocationCountryEnWiki]) extends ProvidedTriePhraseLexicon[LocationCountryEnWiki]
class LocationCountryEsWiki()(implicit mp: ModelProvider[LocationCountryEsWiki]) extends ProvidedTriePhraseLexicon[LocationCountryEsWiki]
class LocationCountryFree()(implicit mp: ModelProvider[LocationCountryFree]) extends ProvidedTriePhraseLexicon[LocationCountryFree]
class LocationIesl()(implicit mp: ModelProvider[LocationIesl]) extends ProvidedTriePhraseLexicon[LocationIesl]
class LocationRedirectWiki()(implicit mp: ModelProvider[LocationRedirectWiki]) extends ProvidedTriePhraseLexicon[LocationRedirectWiki]
class LocationStateEnWiki()(implicit mp: ModelProvider[LocationStateEnWiki]) extends ProvidedTriePhraseLexicon[LocationStateEnWiki]
class LocationStateEsWiki()(implicit mp: ModelProvider[LocationStateEsWiki]) extends ProvidedTriePhraseLexicon[LocationStateEsWiki]
class LocationUndefinedEnWiki()(implicit mp: ModelProvider[LocationUndefinedEnWiki]) extends ProvidedTriePhraseLexicon[LocationUndefinedEnWiki]
class LocationUndefinedEsWiki()(implicit mp: ModelProvider[LocationUndefinedEsWiki]) extends ProvidedTriePhraseLexicon[LocationUndefinedEsWiki]
class LocationWiki()(implicit mp: ModelProvider[LocationWiki]) extends ProvidedTriePhraseLexicon[LocationWiki]
class MiscellaneousIesl()(implicit mp: ModelProvider[MiscellaneousIesl]) extends ProvidedTriePhraseLexicon[MiscellaneousIesl]
class MonthIesl()(implicit mp: ModelProvider[MonthIesl]) extends ProvidedTriePhraseLexicon[MonthIesl]
class OrgSuffixIesl()(implicit mp: ModelProvider[OrgSuffixIesl]) extends ProvidedTriePhraseLexicon[OrgSuffixIesl]
class OrganizationIesl()(implicit mp: ModelProvider[OrganizationIesl]) extends ProvidedTriePhraseLexicon[OrganizationIesl]
class OrganizationOrganizationFree()(implicit mp: ModelProvider[OrganizationOrganizationFree]) extends ProvidedTriePhraseLexicon[OrganizationOrganizationFree]
class OrganizationOrganizationSectorFree()(implicit mp: ModelProvider[OrganizationOrganizationSectorFree]) extends ProvidedTriePhraseLexicon[OrganizationOrganizationSectorFree]
class OrganizationRedirectWiki()(implicit mp: ModelProvider[OrganizationRedirectWiki]) extends ProvidedTriePhraseLexicon[OrganizationRedirectWiki]
class OrganizationWiki()(implicit mp: ModelProvider[OrganizationWiki]) extends ProvidedTriePhraseLexicon[OrganizationWiki]
class PeopleCauseOfDeathFree()(implicit mp: ModelProvider[PeopleCauseOfDeathFree]) extends ProvidedTriePhraseLexicon[PeopleCauseOfDeathFree]
class PeoplePersonFree()(implicit mp: ModelProvider[PeoplePersonFree]) extends ProvidedTriePhraseLexicon[PeoplePersonFree]
class PeopleProfessionFree()(implicit mp: ModelProvider[PeopleProfessionFree]) extends ProvidedTriePhraseLexicon[PeopleProfessionFree]
class PeopleFirstIesl()(implicit mp: ModelProvider[PeopleFirstIesl]) extends ProvidedTriePhraseLexicon[PeopleFirstIesl]
class PeopleHonorificIesl()(implicit mp: ModelProvider[PeopleHonorificIesl]) extends ProvidedTriePhraseLexicon[PeopleHonorificIesl]
class PeopleIesl()(implicit mp: ModelProvider[PeopleIesl]) extends ProvidedTriePhraseLexicon[PeopleIesl]
class PeopleLastIesl()(implicit mp: ModelProvider[PeopleLastIesl]) extends ProvidedTriePhraseLexicon[PeopleLastIesl]
class PeopleRedirectWiki()(implicit mp: ModelProvider[PeopleRedirectWiki]) extends ProvidedTriePhraseLexicon[PeopleRedirectWiki]
class PeopleWiki()(implicit mp: ModelProvider[PeopleWiki]) extends ProvidedTriePhraseLexicon[PeopleWiki]
class ReligionReligionFree()(implicit mp: ModelProvider[ReligionReligionFree]) extends ProvidedTriePhraseLexicon[ReligionReligionFree]
class ReligionReligiousOrganizationFree()(implicit mp: ModelProvider[ReligionReligiousOrganizationFree]) extends ProvidedTriePhraseLexicon[ReligionReligiousOrganizationFree]
