/* Copyright (C) 2008-2016 University of Massachusetts Amherst.
   This file is part of "FACTORIE" (Factor graphs, Imperative, Extensible)
   http://factorie.cs.umass.edu, http://github.com/factorie
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */
package cc.factorie.app.nlp.ner

import cc.factorie.app.nlp.Token
import cc.factorie.variable.CategoricalVectorVar
import cc.factorie.app.nlp.lexicon.StaticLexicons
import cc.factorie.app.nlp.lexicon.LexiconsProvider
import cc.factorie.app.nlp.lemma.LowercaseTokenLemma

class StaticLexiconFeatures(lexicon:StaticLexicons, lang: String) extends NerLexiconFeatures {
    //this block serves to initialize all of the lexicons used by the model before processing
  lexicon.synchronized {
    
    if (lang.equals("en") || lang.equals("all")){
      
    	lexicon.iesl.Month.toString()
    	lexicon.iesl.Day.toString()
    	
    	lexicon.iesl.PersonFirst.toString()
    	lexicon.iesl.PersonFirstHigh.toString()
    	lexicon.iesl.PersonFirstHighest.toString()
    	lexicon.iesl.PersonFirstMedium.toString()
    	
    	lexicon.iesl.PersonLast.toString()
    	lexicon.iesl.PersonLastHigh.toString()
    	lexicon.iesl.PersonLastHighest.toString()
    	lexicon.iesl.PersonLastMedium.toString()
    	
    	lexicon.iesl.PersonHonorific.toString()
    	
    	lexicon.iesl.Company.toString()
    	lexicon.iesl.JobTitle.toString()
    	lexicon.iesl.OrgSuffix.toString()
    	
    	lexicon.iesl.Country.toString()
    	lexicon.iesl.City.toString()
    	lexicon.iesl.PlaceSuffix.toString()
    	lexicon.iesl.UsState.toString()
    	lexicon.iesl.Continents.toString()
    	
    	lexicon.wikipedia.Person.toString()
    	lexicon.wikipedia.Event.toString()
    	lexicon.wikipedia.Location.toString()
    	lexicon.wikipedia.Organization.toString()
    	lexicon.wikipedia.ManMadeThing.toString()
    	lexicon.iesl.Demonym.toString()
    	
    	lexicon.wikipedia.Book.toString()
    	lexicon.wikipedia.Business.toString()
    	lexicon.wikipedia.Film.toString()
    	
    	lexicon.wikipedia.LocationAndRedirect.toString()
    	lexicon.wikipedia.PersonAndRedirect.toString()
    	lexicon.wikipedia.OrganizationAndRedirect.toString()

		lexicon.english.MajorAnimalParenWiki.toString()
		lexicon.english.MajorAnimalRedirectParenWiki.toString()
		lexicon.english.MajorAnimalRedirectWiki.toString()
		lexicon.english.MajorAnimalWiki.toString()
		lexicon.english.MajorAnimalsParenWiki.toString()
		lexicon.english.MajorAnimalsRedirectParenWiki.toString()
		lexicon.english.MajorAnimalsRedirectWiki.toString()
		lexicon.english.MajorAnimalsWiki.toString()
		lexicon.english.MajorBaseFightCrimeTypeFree.toString()
		lexicon.english.MajorBattleDisambiguationWiki.toString()
		lexicon.english.MajorBattleParenWiki.toString()
		lexicon.english.MajorBattleRedirectParenWiki.toString()
		lexicon.english.MajorBattleRedirectWiki.toString()
		lexicon.english.MajorBattleWiki.toString()
		lexicon.english.MajorBattlesDisambiguationWiki.toString()
		lexicon.english.MajorBattlesParenWiki.toString()
		lexicon.english.MajorBattlesRedirectParenWiki.toString()
		lexicon.english.MajorBattlesRedirectWiki.toString()
		lexicon.english.MajorBattlesWiki.toString()
		lexicon.english.MajorBookDisambiguationWiki.toString()
		lexicon.english.MajorBookParenWiki.toString()
		lexicon.english.MajorBookRedirectParenWiki.toString()
		lexicon.english.MajorBookRedirectWiki.toString()
		lexicon.english.MajorBookWiki.toString()
		lexicon.english.MajorBusinessDisambiguationWiki.toString()
		lexicon.english.MajorBusinessJobTitleFree.toString()
		lexicon.english.MajorBusinessParenWiki.toString()
		lexicon.english.MajorBusinessRedirectParenWiki.toString()
		lexicon.english.MajorBusinessRedirectWiki.toString()
		lexicon.english.MajorBusinessWiki.toString()
		lexicon.english.MajorCityIesl.toString()
		lexicon.english.MajorCityParenWiki.toString()
		lexicon.english.MajorCityRedirectParenWiki.toString()
		lexicon.english.MajorCityRedirectWiki.toString()
		lexicon.english.MajorCityWiki.toString()
		lexicon.english.MajorCompanyIesl.toString()
		lexicon.english.MajorCompetitionDisambiguationWiki.toString()
		lexicon.english.MajorCompetitionParenWiki.toString()
		lexicon.english.MajorCompetitionRedirectParenWiki.toString()
		lexicon.english.MajorCompetitionRedirectWiki.toString()
		lexicon.english.MajorCompetitionWiki.toString()
		lexicon.english.MajorContinentsIesl.toString()
		lexicon.english.MajorCountryIesl.toString()
		lexicon.english.MajorCountryParenWiki.toString()
		lexicon.english.MajorCountryRedirectParenWiki.toString()
		lexicon.english.MajorCountryRedirectWiki.toString()
		lexicon.english.MajorCountryWiki.toString()
		lexicon.english.MajorDayIesl.toString()
		lexicon.english.MajorDemonymIesl.toString()
		lexicon.english.MajorDemonymsIesl.toString()
		lexicon.english.MajorEducationEducationalInstitutionFree.toString()
		lexicon.english.MajorEventDisambiguationWiki.toString()
		lexicon.english.MajorEventParenWiki.toString()
		lexicon.english.MajorEventRedirectParenWiki.toString()
		lexicon.english.MajorEventRedirectWiki.toString()
		lexicon.english.MajorEventWiki.toString()
		lexicon.english.MajorEventsDisambiguationWiki.toString()
		lexicon.english.MajorEventsParenWiki.toString()
		lexicon.english.MajorEventsRedirectParenWiki.toString()
		lexicon.english.MajorEventsRedirectWiki.toString()
		lexicon.english.MajorEventsWiki.toString()
		lexicon.english.MajorFilmDisambiguationWiki.toString()
		lexicon.english.MajorFilmParenWiki.toString()
		lexicon.english.MajorFilmRedirectParenWiki.toString()
		lexicon.english.MajorFilmRedirectWiki.toString()
		lexicon.english.MajorFilmWiki.toString()
		lexicon.english.MajorGovernmentPoliticalDistrictFree.toString()
		lexicon.english.MajorGovernmentPoliticalIdeologyFree.toString()
		lexicon.english.MajorGovernmentPoliticalPartyFree.toString()
		lexicon.english.MajorJobTitleIesl.toString()
		lexicon.english.MajorJobtitleIesl.toString()
		lexicon.english.MajorLawLegalSubjectFree.toString()
		lexicon.english.MajorLocationAdministrativeDivisionFree.toString()
		lexicon.english.MajorLocationCitytownFree.toString()
		lexicon.english.MajorLocationCountryFree.toString()
		lexicon.english.MajorLocationDisambiguationWiki.toString()
		lexicon.english.MajorLocationParenWiki.toString()
		lexicon.english.MajorLocationRedirectParenWiki.toString()
		lexicon.english.MajorLocationRedirectWiki.toString()
		lexicon.english.MajorLocationWiki.toString()
		lexicon.english.MajorManMadeThingDisambiguationWiki.toString()
		lexicon.english.MajorManMadeThingParenWiki.toString()
		lexicon.english.MajorManMadeThingRedirectParenWiki.toString()
		lexicon.english.MajorManMadeThingRedirectWiki.toString()
		lexicon.english.MajorManMadeThingWiki.toString()
		lexicon.english.MajorMan_made_thingDisambiguationWiki.toString()
		lexicon.english.MajorMan_made_thingParenWiki.toString()
		lexicon.english.MajorMan_made_thingRedirectParenWiki.toString()
		lexicon.english.MajorMan_made_thingRedirectWiki.toString()
		lexicon.english.MajorMan_made_thingWiki.toString()
		lexicon.english.MajorMoneyIesl.toString()
		lexicon.english.MajorMonthIesl.toString()
		lexicon.english.MajorOrgSuffixIesl.toString()
		lexicon.english.MajorOrganizationDisambiguationWiki.toString()
		lexicon.english.MajorOrganizationOrganizationFree.toString()
		lexicon.english.MajorOrganizationOrganizationSectorFree.toString()
		lexicon.english.MajorOrganizationParenWiki.toString()
		lexicon.english.MajorOrganizationRedirectParenWiki.toString()
		lexicon.english.MajorOrganizationRedirectWiki.toString()
		lexicon.english.MajorOrganizationWiki.toString()
		lexicon.english.MajorPeopleCauseOfDeathFree.toString()
		lexicon.english.MajorPeoplePersonFree.toString()
		lexicon.english.MajorPeopleProfessionFree.toString()
		lexicon.english.MajorPersonDisambiguationWiki.toString()
		lexicon.english.MajorPersonFirstHighIesl.toString()
		lexicon.english.MajorPersonFirstHighestIesl.toString()
		lexicon.english.MajorPersonFirstMediumIesl.toString()
		lexicon.english.MajorPersonHonorificIesl.toString()
		lexicon.english.MajorPersonImproperIesl.toString()
		lexicon.english.MajorPersonLastHighIesl.toString()
		lexicon.english.MajorPersonLastHighestIesl.toString()
		lexicon.english.MajorPersonLastMediumIesl.toString()
		lexicon.english.MajorPersonParenWiki.toString()
		lexicon.english.MajorPersonRedirectParenWiki.toString()
		lexicon.english.MajorPersonRedirectWiki.toString()
		lexicon.english.MajorPersonSuffixIesl.toString()
		lexicon.english.MajorPersonWiki.toString()
		lexicon.english.MajorPlaceSuffixIesl.toString()
		lexicon.english.MajorRedirectDisambiguationWiki.toString()
		lexicon.english.MajorReligionReligionFree.toString()
		lexicon.english.MajorReligionReligiousOrganizationFree.toString()
		lexicon.english.MajorSayIesl.toString()
		lexicon.english.MajorSongDisambiguationWiki.toString()
		lexicon.english.MajorSongParenWiki.toString()
		lexicon.english.MajorSongRedirectParenWiki.toString()
		lexicon.english.MajorSongRedirectWiki.toString()
		lexicon.english.MajorSongWiki.toString()
		lexicon.english.MajorSongsDisambiguationWiki.toString()
		lexicon.english.MajorSongsParenWiki.toString()
		lexicon.english.MajorSongsRedirectParenWiki.toString()
		lexicon.english.MajorSongsRedirectWiki.toString()
		lexicon.english.MajorSongsWiki.toString()
		lexicon.english.MajorUkCountyIesl.toString()
		lexicon.english.MajorUsStateIesl.toString()
		lexicon.english.MajorWaterbodiesParenWiki.toString()
		lexicon.english.MajorWaterbodiesRedirectParenWiki.toString()
		lexicon.english.MajorWaterbodiesRedirectWiki.toString()
		lexicon.english.MajorWaterbodiesWiki.toString()

		lexicon.english.MinorBaseFightCrimeTypeFree.toString()
		lexicon.english.MinorBusinessDisambiguationWiki.toString()
		lexicon.english.MinorBusinessJobTitleFree.toString()
		lexicon.english.MinorBusinessParenWiki.toString()
		lexicon.english.MinorBusinessRedirectParenWiki.toString()
		lexicon.english.MinorBusinessRedirectWiki.toString()
		lexicon.english.MinorBusinessWiki.toString()
		lexicon.english.MinorCityIesl.toString()
		lexicon.english.MinorCityParenWiki.toString()
		lexicon.english.MinorCityRedirectParenWiki.toString()
		lexicon.english.MinorCityRedirectWiki.toString()
		lexicon.english.MinorCityWiki.toString()
		lexicon.english.MinorCompanyIesl.toString()
		lexicon.english.MinorCountryIesl.toString()
		lexicon.english.MinorCountryParenWiki.toString()
		lexicon.english.MinorCountryRedirectParenWiki.toString()
		lexicon.english.MinorCountryRedirectWiki.toString()
		lexicon.english.MinorCountryWiki.toString()
		lexicon.english.MinorEducationEducationalInstitutionFree.toString()
		lexicon.english.MinorGovernmentPoliticalDistrictFree.toString()
		lexicon.english.MinorGovernmentPoliticalIdeologyFree.toString()
		lexicon.english.MinorGovernmentPoliticalPartyFree.toString()
		lexicon.english.MinorJobTitleIesl.toString()
		lexicon.english.MinorJobtitleIesl.toString()
		lexicon.english.MinorLawLegalSubjectFree.toString()
		lexicon.english.MinorLocationAdministrativeDivisionFree.toString()
		lexicon.english.MinorLocationCitytownFree.toString()
		lexicon.english.MinorLocationCountryFree.toString()
		lexicon.english.MinorLocationDisambiguationWiki.toString()
		lexicon.english.MinorLocationParenWiki.toString()
		lexicon.english.MinorLocationRedirectParenWiki.toString()
		lexicon.english.MinorLocationRedirectWiki.toString()
		lexicon.english.MinorLocationWiki.toString()
		lexicon.english.MinorOrgSuffixIesl.toString()
		lexicon.english.MinorOrganizationDisambiguationWiki.toString()
		lexicon.english.MinorOrganizationOrganizationFree.toString()
		lexicon.english.MinorOrganizationOrganizationSectorFree.toString()
		lexicon.english.MinorOrganizationParenWiki.toString()
		lexicon.english.MinorOrganizationRedirectParenWiki.toString()
		lexicon.english.MinorOrganizationRedirectWiki.toString()
		lexicon.english.MinorOrganizationWiki.toString()
		lexicon.english.MinorPeopleCauseOfDeathFree.toString()
		lexicon.english.MinorPeoplePersonFree.toString()
		lexicon.english.MinorPeopleProfessionFree.toString()
		lexicon.english.MinorPersonDisambiguationWiki.toString()
		lexicon.english.MinorPersonFirstHighIesl.toString()
		lexicon.english.MinorPersonFirstHighestIesl.toString()
		lexicon.english.MinorPersonFirstMediumIesl.toString()
		lexicon.english.MinorPersonHonorificIesl.toString()
		lexicon.english.MinorPersonLastHighIesl.toString()
		lexicon.english.MinorPersonLastHighestIesl.toString()
		lexicon.english.MinorPersonLastMediumIesl.toString()
		lexicon.english.MinorPersonParenWiki.toString()
		lexicon.english.MinorPersonRedirectParenWiki.toString()
		lexicon.english.MinorPersonRedirectWiki.toString()
		lexicon.english.MinorPersonWiki.toString()
		lexicon.english.MinorReligionReligionFree.toString()
		lexicon.english.MinorReligionReligiousOrganizationFree.toString()
    }
    
    if (lang.equals("es") || lang.equals("all")){

		lexicon.spanish.Continents.toString()
		lexicon.spanish.Month.toString()
		lexicon.spanish.Day.toString()
		lexicon.spanish.PersonFirst.toString()
		lexicon.spanish.PersonLast.toString()
		lexicon.spanish.Person.toString()
		lexicon.spanish.PersonHonorific.toString()
		lexicon.spanish.Location.toString()
		lexicon.spanish.Organization.toString()
		lexicon.spanish.Miscellaneous.toString()
		lexicon.spanish.OrgSuffix.toString()
		lexicon.spanish.Demonym.toString()


		lexicon.spanish.WikiBook.toString()
		lexicon.spanish.WikiEvent.toString()
		lexicon.spanish.WikiBusiness.toString()
		lexicon.spanish.WikiFilm.toString()
		lexicon.spanish.WikiPerson.toString()
		lexicon.spanish.WikiLocation.toString()
		lexicon.spanish.WikiOrganization.toString()
		lexicon.spanish.WikiLocationAndRedirect.toString()
		lexicon.spanish.WikiPersonAndRedirect.toString()
		lexicon.spanish.WikiOrganizationAndRedirect.toString()


		lexicon.spanish.MajorBaseFightCrimeTypeFree.toString()
		lexicon.spanish.MajorBookWiki.toString()
		lexicon.spanish.MajorBusinessJobTitleFree.toString()
		lexicon.spanish.MajorBusinessWiki.toString()
		lexicon.spanish.MajorContinentsIesl.toString()
		lexicon.spanish.MajorDayIesl.toString()
		lexicon.spanish.MajorDemonymIesl.toString()
		lexicon.spanish.MajorEducationEducationalInstitutionFree.toString()
		lexicon.spanish.MajorEventWiki.toString()
		lexicon.spanish.MajorFilmWiki.toString()
		lexicon.spanish.MajorFirstNameFemaleExtr.toString()
		lexicon.spanish.MajorFirstNameMaleExtr.toString()
		lexicon.spanish.MajorGovernmentPoliticalDistrictFree.toString()
		lexicon.spanish.MajorGovernmentPoliticalIdeologyFree.toString()
		lexicon.spanish.MajorGovernmentPoliticalPartyFree.toString()
		lexicon.spanish.MajorLastNameExtr.toString()
		lexicon.spanish.MajorLawLegalSubjectFree.toString()
		lexicon.spanish.MajorLocationAdministrativeDivisionFree.toString()
		lexicon.spanish.MajorLocationCityOsmp.toString()
		lexicon.spanish.MajorLocationCityWiki.toString()
		lexicon.spanish.MajorLocationCitytownFree.toString()
		lexicon.spanish.MajorLocationCountryWiki.toString()
		lexicon.spanish.MajorLocationCountryFree.toString()
		lexicon.spanish.MajorLocationIesl.toString()
		lexicon.spanish.MajorLocationRedirectWiki.toString()
		lexicon.spanish.MajorLocationStateWiki.toString()
		lexicon.spanish.MajorLocationUndefinedWiki.toString()
		lexicon.spanish.MajorLocationWiki.toString()
		lexicon.spanish.MajorMiscellaneousIesl.toString()
		lexicon.spanish.MajorMonthIesl.toString()
		lexicon.spanish.MajorOrgSuffixIesl.toString()
		lexicon.spanish.MajorOrganizationIesl.toString()
		lexicon.spanish.MajorOrganizationOrganizationFree.toString()
		lexicon.spanish.MajorOrganizationOrganizationSectorFree.toString()
		lexicon.spanish.MajorOrganizationRedirectWiki.toString()
		lexicon.spanish.MajorOrganizationWiki.toString()
		lexicon.spanish.MajorPeopleCauseOfDeathFree.toString()
		lexicon.spanish.MajorPeoplePersonFree.toString()
		lexicon.spanish.MajorPeopleProfessionFree.toString()
		lexicon.spanish.MajorPersonFirstIesl.toString()
		lexicon.spanish.MajorPersonHonorificIesl.toString()
		lexicon.spanish.MajorPersonIesl.toString()
		lexicon.spanish.MajorPersonLastIesl.toString()
		lexicon.spanish.MajorPersonRedirectWiki.toString()
		lexicon.spanish.MajorPersonWiki.toString()
		lexicon.spanish.MajorReligionReligionFree.toString()
		lexicon.spanish.MajorReligionReligiousOrganizationFree.toString()


		lexicon.spanish.MinorBaseFightCrimeTypeFree.toString()
		lexicon.spanish.MinorBusinessJobTitleFree.toString()
		lexicon.spanish.MinorBusinessWiki.toString()
		lexicon.spanish.MinorEducationEducationalInstitutionFree.toString()
		lexicon.spanish.MinorFirstNameFemaleExtr.toString()
		lexicon.spanish.MinorFirstNameMaleExtr.toString()
		lexicon.spanish.MinorGovernmentPoliticalDistrictFree.toString()
		lexicon.spanish.MinorGovernmentPoliticalIdeologyFree.toString()
		lexicon.spanish.MinorGovernmentPoliticalPartyFree.toString()
		lexicon.spanish.MinorLastNameExtr.toString()
		lexicon.spanish.MinorLawLegalSubjectFree.toString()
		lexicon.spanish.MinorLocationAdministrativeDivisionFree.toString()
		lexicon.spanish.MinorLocationCityOsmp.toString()
		lexicon.spanish.MinorLocationCityWiki.toString()
		lexicon.spanish.MinorLocationCitytownFree.toString()
		lexicon.spanish.MinorLocationCountryWiki.toString()
		lexicon.spanish.MinorLocationCountryFree.toString()
		lexicon.spanish.MinorLocationIesl.toString()
		lexicon.spanish.MinorLocationRedirectWiki.toString()
		lexicon.spanish.MinorLocationStateWiki.toString()
		lexicon.spanish.MinorLocationUndefinedWiki.toString()
		lexicon.spanish.MinorLocationWiki.toString()
		lexicon.spanish.MinorOrganizationIesl.toString()
		lexicon.spanish.MinorOrganizationOrganizationFree.toString()
		lexicon.spanish.MinorOrganizationOrganizationSectorFree.toString()
		lexicon.spanish.MinorOrganizationRedirectWiki.toString()
		lexicon.spanish.MinorOrganizationWiki.toString()
		lexicon.spanish.MinorPeopleCauseOfDeathFree.toString()
		lexicon.spanish.MinorPeoplePersonFree.toString()
		lexicon.spanish.MinorPeopleProfessionFree.toString()
		lexicon.spanish.MinorPersonFirstIesl.toString()
		lexicon.spanish.MinorPersonHonorificIesl.toString()
		lexicon.spanish.MinorPersonIesl.toString()
		lexicon.spanish.MinorPersonLastIesl.toString()
		lexicon.spanish.MinorPersonRedirectWiki.toString()
		lexicon.spanish.MinorPersonWiki.toString()
		lexicon.spanish.MinorReligionReligionFree.toString()
		lexicon.spanish.MinorReligionReligiousOrganizationFree.toString()
    }
     
  }
  
  
  
  def addLexiconFeatures(tokenSequence: IndexedSeq[Token], vf: (Token => CategoricalVectorVar[String])) {
    
    if (lang.equals("en") || lang.equals("all")){
         
    	lexicon.iesl.Month.tagText(tokenSequence,vf,"MONTH")
    	lexicon.iesl.Day.tagText(tokenSequence,vf,"DAY")
    	
    	lexicon.iesl.PersonFirst.tagText(tokenSequence,vf,"PERSON-FIRST")
    	lexicon.iesl.PersonFirstHigh.tagText(tokenSequence,vf,"PERSON-FIRST-HIGH")
    	lexicon.iesl.PersonFirstHighest.tagText(tokenSequence,vf,"PERSON-FIRST-HIGHEST")
    	lexicon.iesl.PersonFirstMedium.tagText(tokenSequence,vf,"PERSON-FIRST-MEDIUM")
    	
    	lexicon.iesl.PersonLast.tagText(tokenSequence,vf,"PERSON-LAST")
    	lexicon.iesl.PersonLastHigh.tagText(tokenSequence,vf,"PERSON-LAST-HIGH")
    	lexicon.iesl.PersonLastHighest.tagText(tokenSequence,vf,"PERSON-LAST-HIGHEST")
    	lexicon.iesl.PersonLastMedium.tagText(tokenSequence,vf,"PERSON-LAST-MEDIUM")
    	
    	lexicon.iesl.PersonHonorific.tagText(tokenSequence,vf,"PERSON-HONORIFIC")
    	
    	lexicon.iesl.Company.tagText(tokenSequence,vf,"COMPANY")
    	lexicon.iesl.JobTitle.tagText(tokenSequence,vf,"JOB-TITLE")
    	lexicon.iesl.OrgSuffix.tagText(tokenSequence,vf,"ORG-SUFFIX")
    	
    	lexicon.iesl.Country.tagText(tokenSequence,vf,"COUNTRY")
    	lexicon.iesl.City.tagText(tokenSequence,vf,"CITY")
    	lexicon.iesl.PlaceSuffix.tagText(tokenSequence,vf,"PLACE-SUFFIX")
    	lexicon.iesl.UsState.tagText(tokenSequence,vf,"USSTATE")
    	lexicon.iesl.Continents.tagText(tokenSequence,vf,"CONTINENT")
    	
    	lexicon.wikipedia.Person.tagText(tokenSequence,vf,"WIKI-PERSON")
    	lexicon.wikipedia.Event.tagText(tokenSequence,vf,"WIKI-EVENT")
    	lexicon.wikipedia.Location.tagText(tokenSequence,vf,"WIKI-LOCATION")
    	lexicon.wikipedia.Organization.tagText(tokenSequence,vf,"WIKI-ORG")
    	lexicon.wikipedia.ManMadeThing.tagText(tokenSequence,vf,"MANMADE")
    	lexicon.iesl.Demonym.tagText(tokenSequence,vf,"DEMONYM")
    	
    	lexicon.wikipedia.Book.tagText(tokenSequence,vf,"WIKI-BOOK")
    	lexicon.wikipedia.Business.tagText(tokenSequence,vf,"WIKI-BUSINESS")
    	lexicon.wikipedia.Film.tagText(tokenSequence,vf,"WIKI-FILM")
    	
    	lexicon.wikipedia.LocationAndRedirect.tagText(tokenSequence,vf,"WIKI-LOCATION-REDIRECT")
    	lexicon.wikipedia.PersonAndRedirect.tagText(tokenSequence,vf,"WIKI-PERSON-REDIRECT")
    	lexicon.wikipedia.OrganizationAndRedirect.tagText(tokenSequence,vf,"WIKI-ORG-REDIRECT")

		lexicon.english.MajorAnimalParenWiki.tagText(tokenSequence,vf,"MAJOR-ANIMAL-PAREN-WIKI")
		lexicon.english.MajorAnimalRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-ANIMAL-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorAnimalRedirectWiki.tagText(tokenSequence,vf,"MAJOR-ANIMAL-REDIRECT-WIKI")
		lexicon.english.MajorAnimalWiki.tagText(tokenSequence,vf,"MAJOR-ANIMAL-WIKI")
		lexicon.english.MajorAnimalsParenWiki.tagText(tokenSequence,vf,"MAJOR-ANIMALS-PAREN-WIKI")
		lexicon.english.MajorAnimalsRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-ANIMALS-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorAnimalsRedirectWiki.tagText(tokenSequence,vf,"MAJOR-ANIMALS-REDIRECT-WIKI")
		lexicon.english.MajorAnimalsWiki.tagText(tokenSequence,vf,"MAJOR-ANIMALS-WIKI")
		lexicon.english.MajorBaseFightCrimeTypeFree.tagText(tokenSequence,vf,"MAJOR-BASE-FIGHT-CRIME-TYPE-FREE")
		lexicon.english.MajorBattleDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-BATTLE-DISAMBIGUATION-WIKI")
		lexicon.english.MajorBattleParenWiki.tagText(tokenSequence,vf,"MAJOR-BATTLE-PAREN-WIKI")
		lexicon.english.MajorBattleRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-BATTLE-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorBattleRedirectWiki.tagText(tokenSequence,vf,"MAJOR-BATTLE-REDIRECT-WIKI")
		lexicon.english.MajorBattleWiki.tagText(tokenSequence,vf,"MAJOR-BATTLE-WIKI")
		lexicon.english.MajorBattlesDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-BATTLES-DISAMBIGUATION-WIKI")
		lexicon.english.MajorBattlesParenWiki.tagText(tokenSequence,vf,"MAJOR-BATTLES-PAREN-WIKI")
		lexicon.english.MajorBattlesRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-BATTLES-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorBattlesRedirectWiki.tagText(tokenSequence,vf,"MAJOR-BATTLES-REDIRECT-WIKI")
		lexicon.english.MajorBattlesWiki.tagText(tokenSequence,vf,"MAJOR-BATTLES-WIKI")
		lexicon.english.MajorBookDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-BOOK-DISAMBIGUATION-WIKI")
		lexicon.english.MajorBookParenWiki.tagText(tokenSequence,vf,"MAJOR-BOOK-PAREN-WIKI")
		lexicon.english.MajorBookRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-BOOK-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorBookRedirectWiki.tagText(tokenSequence,vf,"MAJOR-BOOK-REDIRECT-WIKI")
		lexicon.english.MajorBookWiki.tagText(tokenSequence,vf,"MAJOR-BOOK-WIKI")
		lexicon.english.MajorBusinessDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-BUSINESS-DISAMBIGUATION-WIKI")
		lexicon.english.MajorBusinessJobTitleFree.tagText(tokenSequence,vf,"MAJOR-BUSINESS-JOB-TITLE-FREE")
		lexicon.english.MajorBusinessParenWiki.tagText(tokenSequence,vf,"MAJOR-BUSINESS-PAREN-WIKI")
		lexicon.english.MajorBusinessRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-BUSINESS-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorBusinessRedirectWiki.tagText(tokenSequence,vf,"MAJOR-BUSINESS-REDIRECT-WIKI")
		lexicon.english.MajorBusinessWiki.tagText(tokenSequence,vf,"MAJOR-BUSINESS-WIKI")
		lexicon.english.MajorCityIesl.tagText(tokenSequence,vf,"MAJOR-CITY-IESL")
		lexicon.english.MajorCityParenWiki.tagText(tokenSequence,vf,"MAJOR-CITY-PAREN-WIKI")
		lexicon.english.MajorCityRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-CITY-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorCityRedirectWiki.tagText(tokenSequence,vf,"MAJOR-CITY-REDIRECT-WIKI")
		lexicon.english.MajorCityWiki.tagText(tokenSequence,vf,"MAJOR-CITY-WIKI")
		lexicon.english.MajorCompanyIesl.tagText(tokenSequence,vf,"MAJOR-COMPANY-IESL")
		lexicon.english.MajorCompetitionDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-COMPETITION-DISAMBIGUATION-WIKI")
		lexicon.english.MajorCompetitionParenWiki.tagText(tokenSequence,vf,"MAJOR-COMPETITION-PAREN-WIKI")
		lexicon.english.MajorCompetitionRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-COMPETITION-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorCompetitionRedirectWiki.tagText(tokenSequence,vf,"MAJOR-COMPETITION-REDIRECT-WIKI")
		lexicon.english.MajorCompetitionWiki.tagText(tokenSequence,vf,"MAJOR-COMPETITION-WIKI")
		lexicon.english.MajorContinentsIesl.tagText(tokenSequence,vf,"MAJOR-CONTINENTS-IESL")
		lexicon.english.MajorCountryIesl.tagText(tokenSequence,vf,"MAJOR-COUNTRY-IESL")
		lexicon.english.MajorCountryParenWiki.tagText(tokenSequence,vf,"MAJOR-COUNTRY-PAREN-WIKI")
		lexicon.english.MajorCountryRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-COUNTRY-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorCountryRedirectWiki.tagText(tokenSequence,vf,"MAJOR-COUNTRY-REDIRECT-WIKI")
		lexicon.english.MajorCountryWiki.tagText(tokenSequence,vf,"MAJOR-COUNTRY-WIKI")
		lexicon.english.MajorDayIesl.tagText(tokenSequence,vf,"MAJOR-DAY-IESL")
		lexicon.english.MajorDemonymIesl.tagText(tokenSequence,vf,"MAJOR-DEMONYM-IESL")
		lexicon.english.MajorDemonymsIesl.tagText(tokenSequence,vf,"MAJOR-DEMONYMS-IESL")
		lexicon.english.MajorEducationEducationalInstitutionFree.tagText(tokenSequence,vf,"MAJOR-EDUCATION-EDUCATIONAL-INSTITUTION-FREE")
		lexicon.english.MajorEventDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-EVENT-DISAMBIGUATION-WIKI")
		lexicon.english.MajorEventParenWiki.tagText(tokenSequence,vf,"MAJOR-EVENT-PAREN-WIKI")
		lexicon.english.MajorEventRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-EVENT-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorEventRedirectWiki.tagText(tokenSequence,vf,"MAJOR-EVENT-REDIRECT-WIKI")
		lexicon.english.MajorEventWiki.tagText(tokenSequence,vf,"MAJOR-EVENT-WIKI")
		lexicon.english.MajorEventsDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-EVENTS-DISAMBIGUATION-WIKI")
		lexicon.english.MajorEventsParenWiki.tagText(tokenSequence,vf,"MAJOR-EVENTS-PAREN-WIKI")
		lexicon.english.MajorEventsRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-EVENTS-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorEventsRedirectWiki.tagText(tokenSequence,vf,"MAJOR-EVENTS-REDIRECT-WIKI")
		lexicon.english.MajorEventsWiki.tagText(tokenSequence,vf,"MAJOR-EVENTS-WIKI")
		lexicon.english.MajorFilmDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-FILM-DISAMBIGUATION-WIKI")
		lexicon.english.MajorFilmParenWiki.tagText(tokenSequence,vf,"MAJOR-FILM-PAREN-WIKI")
		lexicon.english.MajorFilmRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-FILM-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorFilmRedirectWiki.tagText(tokenSequence,vf,"MAJOR-FILM-REDIRECT-WIKI")
		lexicon.english.MajorFilmWiki.tagText(tokenSequence,vf,"MAJOR-FILM-WIKI")
		lexicon.english.MajorGovernmentPoliticalDistrictFree.tagText(tokenSequence,vf,"MAJOR-GOVERNMENT-POLITICAL-DISTRICT-FREE")
		lexicon.english.MajorGovernmentPoliticalIdeologyFree.tagText(tokenSequence,vf,"MAJOR-GOVERNMENT-POLITICAL-IDEOLOGY-FREE")
		lexicon.english.MajorGovernmentPoliticalPartyFree.tagText(tokenSequence,vf,"MAJOR-GOVERNMENT-POLITICAL-PARTY-FREE")
		lexicon.english.MajorJobTitleIesl.tagText(tokenSequence,vf,"MAJOR-JOB-TITLE-IESL")
		lexicon.english.MajorJobtitleIesl.tagText(tokenSequence,vf,"MAJOR-JOBTITLE-IESL")
		lexicon.english.MajorLawLegalSubjectFree.tagText(tokenSequence,vf,"MAJOR-LAW-LEGAL-SUBJECT-FREE")
		lexicon.english.MajorLocationAdministrativeDivisionFree.tagText(tokenSequence,vf,"MAJOR-LOCATION-ADMINISTRATIVE-DIVISION-FREE")
		lexicon.english.MajorLocationCitytownFree.tagText(tokenSequence,vf,"MAJOR-LOCATION-CITYTOWN-FREE")
		lexicon.english.MajorLocationCountryFree.tagText(tokenSequence,vf,"MAJOR-LOCATION-COUNTRY-FREE")
		lexicon.english.MajorLocationDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-DISAMBIGUATION-WIKI")
		lexicon.english.MajorLocationParenWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-PAREN-WIKI")
		lexicon.english.MajorLocationRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorLocationRedirectWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-REDIRECT-WIKI")
		lexicon.english.MajorLocationWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-WIKI")
		lexicon.english.MajorManMadeThingDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-MAN-MADE-THING-DISAMBIGUATION-WIKI")
		lexicon.english.MajorManMadeThingParenWiki.tagText(tokenSequence,vf,"MAJOR-MAN-MADE-THING-PAREN-WIKI")
		lexicon.english.MajorManMadeThingRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-MAN-MADE-THING-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorManMadeThingRedirectWiki.tagText(tokenSequence,vf,"MAJOR-MAN-MADE-THING-REDIRECT-WIKI")
		lexicon.english.MajorManMadeThingWiki.tagText(tokenSequence,vf,"MAJOR-MAN-MADE-THING-WIKI")
		lexicon.english.MajorMan_made_thingDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-MAN_MADE_THING-DISAMBIGUATION-WIKI")
		lexicon.english.MajorMan_made_thingParenWiki.tagText(tokenSequence,vf,"MAJOR-MAN_MADE_THING-PAREN-WIKI")
		lexicon.english.MajorMan_made_thingRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-MAN_MADE_THING-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorMan_made_thingRedirectWiki.tagText(tokenSequence,vf,"MAJOR-MAN_MADE_THING-REDIRECT-WIKI")
		lexicon.english.MajorMan_made_thingWiki.tagText(tokenSequence,vf,"MAJOR-MAN_MADE_THING-WIKI")
		lexicon.english.MajorMoneyIesl.tagText(tokenSequence,vf,"MAJOR-MONEY-IESL")
		lexicon.english.MajorMonthIesl.tagText(tokenSequence,vf,"MAJOR-MONTH-IESL")
		lexicon.english.MajorOrgSuffixIesl.tagText(tokenSequence,vf,"MAJOR-ORG-SUFFIX-IESL")
		lexicon.english.MajorOrganizationDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-DISAMBIGUATION-WIKI")
		lexicon.english.MajorOrganizationOrganizationFree.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-ORGANIZATION-FREE")
		lexicon.english.MajorOrganizationOrganizationSectorFree.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-ORGANIZATION-SECTOR-FREE")
		lexicon.english.MajorOrganizationParenWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-PAREN-WIKI")
		lexicon.english.MajorOrganizationRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorOrganizationRedirectWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-REDIRECT-WIKI")
		lexicon.english.MajorOrganizationWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-WIKI")
		lexicon.english.MajorPeopleCauseOfDeathFree.tagText(tokenSequence,vf,"MAJOR-PEOPLE-CAUSE-OF-DEATH-FREE")
		lexicon.english.MajorPeoplePersonFree.tagText(tokenSequence,vf,"MAJOR-PEOPLE-PERSON-FREE")
		lexicon.english.MajorPeopleProfessionFree.tagText(tokenSequence,vf,"MAJOR-PEOPLE-PROFESSION-FREE")
		lexicon.english.MajorPersonDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-DISAMBIGUATION-WIKI")
		lexicon.english.MajorPersonFirstHighIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-FIRST-HIGH-IESL")
		lexicon.english.MajorPersonFirstHighestIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-FIRST-HIGHEST-IESL")
		lexicon.english.MajorPersonFirstMediumIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-FIRST-MEDIUM-IESL")
		lexicon.english.MajorPersonHonorificIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-HONORIFIC-IESL")
		lexicon.english.MajorPersonImproperIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-IMPROPER-IESL")
		lexicon.english.MajorPersonLastHighIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-LAST-HIGH-IESL")
		lexicon.english.MajorPersonLastHighestIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-LAST-HIGHEST-IESL")
		lexicon.english.MajorPersonLastMediumIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-LAST-MEDIUM-IESL")
		lexicon.english.MajorPersonParenWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-PAREN-WIKI")
		lexicon.english.MajorPersonRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorPersonRedirectWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-REDIRECT-WIKI")
		lexicon.english.MajorPersonSuffixIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-SUFFIX-IESL")
		lexicon.english.MajorPersonWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-WIKI")
		lexicon.english.MajorPlaceSuffixIesl.tagText(tokenSequence,vf,"MAJOR-PLACE-SUFFIX-IESL")
		lexicon.english.MajorRedirectDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-REDIRECT-DISAMBIGUATION-WIKI")
		lexicon.english.MajorReligionReligionFree.tagText(tokenSequence,vf,"MAJOR-RELIGION-RELIGION-FREE")
		lexicon.english.MajorReligionReligiousOrganizationFree.tagText(tokenSequence,vf,"MAJOR-RELIGION-RELIGIOUS-ORGANIZATION-FREE")
		lexicon.english.MajorSayIesl.tagText(tokenSequence,vf,"MAJOR-SAY-IESL")
		lexicon.english.MajorSongDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-SONG-DISAMBIGUATION-WIKI")
		lexicon.english.MajorSongParenWiki.tagText(tokenSequence,vf,"MAJOR-SONG-PAREN-WIKI")
		lexicon.english.MajorSongRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-SONG-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorSongRedirectWiki.tagText(tokenSequence,vf,"MAJOR-SONG-REDIRECT-WIKI")
		lexicon.english.MajorSongWiki.tagText(tokenSequence,vf,"MAJOR-SONG-WIKI")
		lexicon.english.MajorSongsDisambiguationWiki.tagText(tokenSequence,vf,"MAJOR-SONGS-DISAMBIGUATION-WIKI")
		lexicon.english.MajorSongsParenWiki.tagText(tokenSequence,vf,"MAJOR-SONGS-PAREN-WIKI")
		lexicon.english.MajorSongsRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-SONGS-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorSongsRedirectWiki.tagText(tokenSequence,vf,"MAJOR-SONGS-REDIRECT-WIKI")
		lexicon.english.MajorSongsWiki.tagText(tokenSequence,vf,"MAJOR-SONGS-WIKI")
		lexicon.english.MajorUkCountyIesl.tagText(tokenSequence,vf,"MAJOR-UK-COUNTY-IESL")
		lexicon.english.MajorUsStateIesl.tagText(tokenSequence,vf,"MAJOR-US-STATE-IESL")
		lexicon.english.MajorWaterbodiesParenWiki.tagText(tokenSequence,vf,"MAJOR-WATERBODIES-PAREN-WIKI")
		lexicon.english.MajorWaterbodiesRedirectParenWiki.tagText(tokenSequence,vf,"MAJOR-WATERBODIES-REDIRECT-PAREN-WIKI")
		lexicon.english.MajorWaterbodiesRedirectWiki.tagText(tokenSequence,vf,"MAJOR-WATERBODIES-REDIRECT-WIKI")
		lexicon.english.MajorWaterbodiesWiki.tagText(tokenSequence,vf,"MAJOR-WATERBODIES-WIKI")


		lexicon.english.MinorBaseFightCrimeTypeFree.tagText(tokenSequence,vf,"MINOR-BASE-FIGHT-CRIME-TYPE-FREE")
		lexicon.english.MinorBusinessDisambiguationWiki.tagText(tokenSequence,vf,"MINOR-BUSINESS-DISAMBIGUATION-WIKI")
		lexicon.english.MinorBusinessJobTitleFree.tagText(tokenSequence,vf,"MINOR-BUSINESS-JOB-TITLE-FREE")
		lexicon.english.MinorBusinessParenWiki.tagText(tokenSequence,vf,"MINOR-BUSINESS-PAREN-WIKI")
		lexicon.english.MinorBusinessRedirectParenWiki.tagText(tokenSequence,vf,"MINOR-BUSINESS-REDIRECT-PAREN-WIKI")
		lexicon.english.MinorBusinessRedirectWiki.tagText(tokenSequence,vf,"MINOR-BUSINESS-REDIRECT-WIKI")
		lexicon.english.MinorBusinessWiki.tagText(tokenSequence,vf,"MINOR-BUSINESS-WIKI")
		lexicon.english.MinorCityIesl.tagText(tokenSequence,vf,"MINOR-CITY-IESL")
		lexicon.english.MinorCityParenWiki.tagText(tokenSequence,vf,"MINOR-CITY-PAREN-WIKI")
		lexicon.english.MinorCityRedirectParenWiki.tagText(tokenSequence,vf,"MINOR-CITY-REDIRECT-PAREN-WIKI")
		lexicon.english.MinorCityRedirectWiki.tagText(tokenSequence,vf,"MINOR-CITY-REDIRECT-WIKI")
		lexicon.english.MinorCityWiki.tagText(tokenSequence,vf,"MINOR-CITY-WIKI")
		lexicon.english.MinorCompanyIesl.tagText(tokenSequence,vf,"MINOR-COMPANY-IESL")
		lexicon.english.MinorCountryIesl.tagText(tokenSequence,vf,"MINOR-COUNTRY-IESL")
		lexicon.english.MinorCountryParenWiki.tagText(tokenSequence,vf,"MINOR-COUNTRY-PAREN-WIKI")
		lexicon.english.MinorCountryRedirectParenWiki.tagText(tokenSequence,vf,"MINOR-COUNTRY-REDIRECT-PAREN-WIKI")
		lexicon.english.MinorCountryRedirectWiki.tagText(tokenSequence,vf,"MINOR-COUNTRY-REDIRECT-WIKI")
		lexicon.english.MinorCountryWiki.tagText(tokenSequence,vf,"MINOR-COUNTRY-WIKI")
		lexicon.english.MinorEducationEducationalInstitutionFree.tagText(tokenSequence,vf,"MINOR-EDUCATION-EDUCATIONAL-INSTITUTION-FREE")
		lexicon.english.MinorGovernmentPoliticalDistrictFree.tagText(tokenSequence,vf,"MINOR-GOVERNMENT-POLITICAL-DISTRICT-FREE")
		lexicon.english.MinorGovernmentPoliticalIdeologyFree.tagText(tokenSequence,vf,"MINOR-GOVERNMENT-POLITICAL-IDEOLOGY-FREE")
		lexicon.english.MinorGovernmentPoliticalPartyFree.tagText(tokenSequence,vf,"MINOR-GOVERNMENT-POLITICAL-PARTY-FREE")
		lexicon.english.MinorJobTitleIesl.tagText(tokenSequence,vf,"MINOR-JOB-TITLE-IESL")
		lexicon.english.MinorJobtitleIesl.tagText(tokenSequence,vf,"MINOR-JOBTITLE-IESL")
		lexicon.english.MinorLawLegalSubjectFree.tagText(tokenSequence,vf,"MINOR-LAW-LEGAL-SUBJECT-FREE")
		lexicon.english.MinorLocationAdministrativeDivisionFree.tagText(tokenSequence,vf,"MINOR-LOCATION-ADMINISTRATIVE-DIVISION-FREE")
		lexicon.english.MinorLocationCitytownFree.tagText(tokenSequence,vf,"MINOR-LOCATION-CITYTOWN-FREE")
		lexicon.english.MinorLocationCountryFree.tagText(tokenSequence,vf,"MINOR-LOCATION-COUNTRY-FREE")
		lexicon.english.MinorLocationDisambiguationWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-DISAMBIGUATION-WIKI")
		lexicon.english.MinorLocationParenWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-PAREN-WIKI")
		lexicon.english.MinorLocationRedirectParenWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-REDIRECT-PAREN-WIKI")
		lexicon.english.MinorLocationRedirectWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-REDIRECT-WIKI")
		lexicon.english.MinorLocationWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-WIKI")
		lexicon.english.MinorOrgSuffixIesl.tagText(tokenSequence,vf,"MINOR-ORG-SUFFIX-IESL")
		lexicon.english.MinorOrganizationDisambiguationWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-DISAMBIGUATION-WIKI")
		lexicon.english.MinorOrganizationOrganizationFree.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-ORGANIZATION-FREE")
		lexicon.english.MinorOrganizationOrganizationSectorFree.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-ORGANIZATION-SECTOR-FREE")
		lexicon.english.MinorOrganizationParenWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-PAREN-WIKI")
		lexicon.english.MinorOrganizationRedirectParenWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-REDIRECT-PAREN-WIKI")
		lexicon.english.MinorOrganizationRedirectWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-REDIRECT-WIKI")
		lexicon.english.MinorOrganizationWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-WIKI")
		lexicon.english.MinorPeopleCauseOfDeathFree.tagText(tokenSequence,vf,"MINOR-PEOPLE-CAUSE-OF-DEATH-FREE")
		lexicon.english.MinorPeoplePersonFree.tagText(tokenSequence,vf,"MINOR-PEOPLE-PERSON-FREE")
		lexicon.english.MinorPeopleProfessionFree.tagText(tokenSequence,vf,"MINOR-PEOPLE-PROFESSION-FREE")
		lexicon.english.MinorPersonDisambiguationWiki.tagText(tokenSequence,vf,"MINOR-PERSON-DISAMBIGUATION-WIKI")
		lexicon.english.MinorPersonFirstHighIesl.tagText(tokenSequence,vf,"MINOR-PERSON-FIRST-HIGH-IESL")
		lexicon.english.MinorPersonFirstHighestIesl.tagText(tokenSequence,vf,"MINOR-PERSON-FIRST-HIGHEST-IESL")
		lexicon.english.MinorPersonFirstMediumIesl.tagText(tokenSequence,vf,"MINOR-PERSON-FIRST-MEDIUM-IESL")
		lexicon.english.MinorPersonHonorificIesl.tagText(tokenSequence,vf,"MINOR-PERSON-HONORIFIC-IESL")
		lexicon.english.MinorPersonLastHighIesl.tagText(tokenSequence,vf,"MINOR-PERSON-LAST-HIGH-IESL")
		lexicon.english.MinorPersonLastHighestIesl.tagText(tokenSequence,vf,"MINOR-PERSON-LAST-HIGHEST-IESL")
		lexicon.english.MinorPersonLastMediumIesl.tagText(tokenSequence,vf,"MINOR-PERSON-LAST-MEDIUM-IESL")
		lexicon.english.MinorPersonParenWiki.tagText(tokenSequence,vf,"MINOR-PERSON-PAREN-WIKI")
		lexicon.english.MinorPersonRedirectParenWiki.tagText(tokenSequence,vf,"MINOR-PERSON-REDIRECT-PAREN-WIKI")
		lexicon.english.MinorPersonRedirectWiki.tagText(tokenSequence,vf,"MINOR-PERSON-REDIRECT-WIKI")
		lexicon.english.MinorPersonWiki.tagText(tokenSequence,vf,"MINOR-PERSON-WIKI")
		lexicon.english.MinorReligionReligionFree.tagText(tokenSequence,vf,"MINOR-RELIGION-RELIGION-FREE")
		lexicon.english.MinorReligionReligiousOrganizationFree.tagText(tokenSequence,vf,"MINOR-RELIGION-RELIGIOUS-ORGANIZATION-FREE")
	}

    if (lang.equals("es") || lang.equals("all")){

		lexicon.spanish.Continents.tagText(tokenSequence,vf,"CONTINENT")
		lexicon.spanish.Month.tagText(tokenSequence,vf,"MONTH")
		lexicon.spanish.Day.tagText(tokenSequence,vf,"DAY")
		lexicon.spanish.PersonFirst.tagText(tokenSequence,vf,"PERSON-FIRST")
		lexicon.spanish.PersonLast.tagText(tokenSequence,vf,"PERSON-LAST")
		lexicon.spanish.Person.tagText(tokenSequence,vf,"PERSON")
		lexicon.spanish.Location.tagText(tokenSequence,vf,"LOCATION")
		lexicon.spanish.Organization.tagText(tokenSequence,vf,"ORGANIZATION")
		lexicon.spanish.Miscellaneous.tagText(tokenSequence,vf,"MISCELLANEOUS")
		lexicon.spanish.PersonHonorific.tagText(tokenSequence,vf,"PERSON-HONORIFIC")
		lexicon.spanish.OrgSuffix.tagText(tokenSequence,vf,"ORG-SUFFIX")
		lexicon.spanish.Demonym.tagText(tokenSequence,vf,"DEMONYM")


		lexicon.spanish.WikiBook.tagText(tokenSequence,vf,"WIKI-BOOK")
		lexicon.spanish.WikiEvent.tagText(tokenSequence,vf,"WIKI-EVENT")
		lexicon.spanish.WikiFilm.tagText(tokenSequence,vf,"WIKI-FILM")
		lexicon.spanish.WikiBusiness.tagText(tokenSequence,vf,"WIKI-BUSINESS")
		lexicon.spanish.WikiPerson.tagText(tokenSequence,vf,"WIKI-PERSON")
		lexicon.spanish.WikiLocation.tagText(tokenSequence,vf,"WIKI-LOCATION")
		lexicon.spanish.WikiOrganization.tagText(tokenSequence,vf,"WIKI-ORG")
		lexicon.spanish.WikiLocationAndRedirect.tagText(tokenSequence,vf,"WIKI-LOCATION-REDIRECT")
		lexicon.spanish.WikiPersonAndRedirect.tagText(tokenSequence,vf,"WIKI-PERSON-REDIRECT")
		lexicon.spanish.WikiOrganizationAndRedirect.tagText(tokenSequence,vf,"WIKI-ORG-REDIRECT")


		lexicon.spanish.MajorBaseFightCrimeTypeFree.tagText(tokenSequence,vf,"MAJOR-BASE-FIGHT-CRIME-TYPE-FREE")
		lexicon.spanish.MajorBookWiki.tagText(tokenSequence,vf,"MAJOR-BOOK-WIKI")
		lexicon.spanish.MajorBusinessJobTitleFree.tagText(tokenSequence,vf,"MAJOR-BUSINESS-JOB-TITLE-FREE")
		lexicon.spanish.MajorBusinessWiki.tagText(tokenSequence,vf,"MAJOR-BUSINESS-WIKI")
		lexicon.spanish.MajorContinentsIesl.tagText(tokenSequence,vf,"MAJOR-CONTINENTS-IESL")
		lexicon.spanish.MajorDayIesl.tagText(tokenSequence,vf,"MAJOR-DAY-IESL")
		lexicon.spanish.MajorDemonymIesl.tagText(tokenSequence,vf,"MAJOR-DEMONYM-IESL")
		lexicon.spanish.MajorEducationEducationalInstitutionFree.tagText(tokenSequence,vf,"MAJOR-EDUCATION-EDUCATIONAL-INSTITUTION-FREE")
		lexicon.spanish.MajorEventWiki.tagText(tokenSequence,vf,"MAJOR-EVENT-WIKI")
		lexicon.spanish.MajorFilmWiki.tagText(tokenSequence,vf,"MAJOR-FILM-WIKI")
		lexicon.spanish.MajorFirstNameFemaleExtr.tagText(tokenSequence,vf,"MAJOR-FIRST-NAME-FEMALE-EXTR")
		lexicon.spanish.MajorFirstNameMaleExtr.tagText(tokenSequence,vf,"MAJOR-FIRST-NAME-MALE-EXTR")
		lexicon.spanish.MajorGovernmentPoliticalDistrictFree.tagText(tokenSequence,vf,"MAJOR-GOVERNMENT-POLITICAL-DISTRICT-FREE")
		lexicon.spanish.MajorGovernmentPoliticalIdeologyFree.tagText(tokenSequence,vf,"MAJOR-GOVERNMENT-POLITICAL-IDEOLOGY-FREE")
		lexicon.spanish.MajorGovernmentPoliticalPartyFree.tagText(tokenSequence,vf,"MAJOR-GOVERNMENT-POLITICAL-PARTY-FREE")
		lexicon.spanish.MajorLastNameExtr.tagText(tokenSequence,vf,"MAJOR-LAST-NAME-EXTR")
		lexicon.spanish.MajorLawLegalSubjectFree.tagText(tokenSequence,vf,"MAJOR-LAW-LEGAL-SUBJECT-FREE")
		lexicon.spanish.MajorLocationAdministrativeDivisionFree.tagText(tokenSequence,vf,"MAJOR-LOCATION-ADMINISTRATIVE-DIVISION-FREE")
		lexicon.spanish.MajorLocationCityOsmp.tagText(tokenSequence,vf,"MAJOR-LOCATION-CITY-OSMP")
		lexicon.spanish.MajorLocationCityWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-CITY-WIKI")
		lexicon.spanish.MajorLocationCitytownFree.tagText(tokenSequence,vf,"MAJOR-LOCATION-CITYTOWN-FREE")
		lexicon.spanish.MajorLocationCountryWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-COUNTRY-WIKI")
		lexicon.spanish.MajorLocationCountryFree.tagText(tokenSequence,vf,"MAJOR-LOCATION-COUNTRY-FREE")
		lexicon.spanish.MajorLocationIesl.tagText(tokenSequence,vf,"MAJOR-LOCATION-IESL")
		lexicon.spanish.MajorLocationRedirectWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-REDIRECT-WIKI")
		lexicon.spanish.MajorLocationStateWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-STATE-WIKI")
		lexicon.spanish.MajorLocationUndefinedWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-UNDEFINED-WIKI")
		lexicon.spanish.MajorLocationWiki.tagText(tokenSequence,vf,"MAJOR-LOCATION-WIKI")
		lexicon.spanish.MajorMiscellaneousIesl.tagText(tokenSequence,vf,"MAJOR-MISCELLANEOUS-IESL")
		lexicon.spanish.MajorMonthIesl.tagText(tokenSequence,vf,"MAJOR-MONTH-IESL")
		lexicon.spanish.MajorOrgSuffixIesl.tagText(tokenSequence,vf,"MAJOR-ORG-SUFFIX-IESL")
		lexicon.spanish.MajorOrganizationIesl.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-IESL")
		lexicon.spanish.MajorOrganizationOrganizationFree.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-ORGANIZATION-FREE")
		lexicon.spanish.MajorOrganizationOrganizationSectorFree.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-ORGANIZATION-SECTOR-FREE")
		lexicon.spanish.MajorOrganizationRedirectWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-REDIRECT-WIKI")
		lexicon.spanish.MajorOrganizationWiki.tagText(tokenSequence,vf,"MAJOR-ORGANIZATION-WIKI")
		lexicon.spanish.MajorPeopleCauseOfDeathFree.tagText(tokenSequence,vf,"MAJOR-PEOPLE-CAUSE-OF-DEATH-FREE")
		lexicon.spanish.MajorPeoplePersonFree.tagText(tokenSequence,vf,"MAJOR-PEOPLE-PERSON-FREE")
		lexicon.spanish.MajorPeopleProfessionFree.tagText(tokenSequence,vf,"MAJOR-PEOPLE-PROFESSION-FREE")
		lexicon.spanish.MajorPersonFirstIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-FIRST-IESL")
		lexicon.spanish.MajorPersonHonorificIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-HONORIFIC-IESL")
		lexicon.spanish.MajorPersonIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-IESL")
		lexicon.spanish.MajorPersonLastIesl.tagText(tokenSequence,vf,"MAJOR-PERSON-LAST-IESL")
		lexicon.spanish.MajorPersonRedirectWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-REDIRECT-WIKI")
		lexicon.spanish.MajorPersonWiki.tagText(tokenSequence,vf,"MAJOR-PERSON-WIKI")
		lexicon.spanish.MajorReligionReligionFree.tagText(tokenSequence,vf,"MAJOR-RELIGION-RELIGION-FREE")
		lexicon.spanish.MajorReligionReligiousOrganizationFree.tagText(tokenSequence,vf,"MAJOR-RELIGION-RELIGIOUS-ORGANIZATION-FREE")


		lexicon.spanish.MinorBaseFightCrimeTypeFree.tagText(tokenSequence,vf,"MINOR-BASE-FIGHT-CRIME-TYPE-FREE")
		lexicon.spanish.MinorBusinessJobTitleFree.tagText(tokenSequence,vf,"MINOR-BUSINESS-JOB-TITLE-FREE")
		lexicon.spanish.MinorBusinessWiki.tagText(tokenSequence,vf,"MINOR-BUSINESS-WIKI")
		lexicon.spanish.MinorEducationEducationalInstitutionFree.tagText(tokenSequence,vf,"MINOR-EDUCATION-EDUCATIONAL-INSTITUTION-FREE")
		lexicon.spanish.MinorFirstNameFemaleExtr.tagText(tokenSequence,vf,"MINOR-FIRST-NAME-FEMALE-EXTR")
		lexicon.spanish.MinorFirstNameMaleExtr.tagText(tokenSequence,vf,"MINOR-FIRST-NAME-MALE-EXTR")
		lexicon.spanish.MinorGovernmentPoliticalDistrictFree.tagText(tokenSequence,vf,"MINOR-GOVERNMENT-POLITICAL-DISTRICT-FREE")
		lexicon.spanish.MinorGovernmentPoliticalIdeologyFree.tagText(tokenSequence,vf,"MINOR-GOVERNMENT-POLITICAL-IDEOLOGY-FREE")
		lexicon.spanish.MinorGovernmentPoliticalPartyFree.tagText(tokenSequence,vf,"MINOR-GOVERNMENT-POLITICAL-PARTY-FREE")
		lexicon.spanish.MinorLastNameExtr.tagText(tokenSequence,vf,"MINOR-LAST-NAME-EXTR")
		lexicon.spanish.MinorLawLegalSubjectFree.tagText(tokenSequence,vf,"MINOR-LAW-LEGAL-SUBJECT-FREE")
		lexicon.spanish.MinorLocationAdministrativeDivisionFree.tagText(tokenSequence,vf,"MINOR-LOCATION-ADMINISTRATIVE-DIVISION-FREE")
		lexicon.spanish.MinorLocationCityOsmp.tagText(tokenSequence,vf,"MINOR-LOCATION-CITY-OSMP")
		lexicon.spanish.MinorLocationCityWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-CITY-WIKI")
		lexicon.spanish.MinorLocationCitytownFree.tagText(tokenSequence,vf,"MINOR-LOCATION-CITYTOWN-FREE")
		lexicon.spanish.MinorLocationCountryWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-COUNTRY-WIKI")
		lexicon.spanish.MinorLocationCountryFree.tagText(tokenSequence,vf,"MINOR-LOCATION-COUNTRY-FREE")
		lexicon.spanish.MinorLocationIesl.tagText(tokenSequence,vf,"MINOR-LOCATION-IESL")
		lexicon.spanish.MinorLocationRedirectWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-REDIRECT-WIKI")
		lexicon.spanish.MinorLocationStateWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-STATE-WIKI")
		lexicon.spanish.MinorLocationUndefinedWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-UNDEFINED-WIKI")
		lexicon.spanish.MinorLocationWiki.tagText(tokenSequence,vf,"MINOR-LOCATION-WIKI")
		lexicon.spanish.MinorOrganizationIesl.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-IESL")
		lexicon.spanish.MinorOrganizationOrganizationFree.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-ORGANIZATION-FREE")
		lexicon.spanish.MinorOrganizationOrganizationSectorFree.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-ORGANIZATION-SECTOR-FREE")
		lexicon.spanish.MinorOrganizationRedirectWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-REDIRECT-WIKI")
		lexicon.spanish.MinorOrganizationWiki.tagText(tokenSequence,vf,"MINOR-ORGANIZATION-WIKI")
		lexicon.spanish.MinorPeopleCauseOfDeathFree.tagText(tokenSequence,vf,"MINOR-PEOPLE-CAUSE-OF-DEATH-FREE")
		lexicon.spanish.MinorPeoplePersonFree.tagText(tokenSequence,vf,"MINOR-PEOPLE-PERSON-FREE")
		lexicon.spanish.MinorPeopleProfessionFree.tagText(tokenSequence,vf,"MINOR-PEOPLE-PROFESSION-FREE")
		lexicon.spanish.MinorPersonFirstIesl.tagText(tokenSequence,vf,"MINOR-PERSON-FIRST-IESL")
		lexicon.spanish.MinorPersonHonorificIesl.tagText(tokenSequence,vf,"MINOR-PERSON-HONORIFIC-IESL")
		lexicon.spanish.MinorPersonIesl.tagText(tokenSequence,vf,"MINOR-PERSON-IESL")
		lexicon.spanish.MinorPersonLastIesl.tagText(tokenSequence,vf,"MINOR-PERSON-LAST-IESL")
		lexicon.spanish.MinorPersonRedirectWiki.tagText(tokenSequence,vf,"MINOR-PERSON-REDIRECT-WIKI")
		lexicon.spanish.MinorPersonWiki.tagText(tokenSequence,vf,"MINOR-PERSON-WIKI")
		lexicon.spanish.MinorReligionReligionFree.tagText(tokenSequence,vf,"MINOR-RELIGION-RELIGION-FREE")
		lexicon.spanish.MinorReligionReligiousOrganizationFree.tagText(tokenSequence,vf,"MINOR-RELIGION-RELIGIOUS-ORGANIZATION-FREE")
	}

  }

}

object StaticLexiconFeatures{
  def apply(lang: String = "en"): StaticLexiconFeatures = {
    new StaticLexiconFeatures(new StaticLexicons()(LexiconsProvider.classpath()), lang)
  }
}